version: '3.8'

services:
  backend:
    build:
      context: .  # Build context for the Laravel backend and React frontend
      dockerfile: Dockerfile  # Specify the Dockerfile
    volumes:
    - .:/var/www:cached
    networks:
      - my-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
